var settings = {
  allowFuture: false,
  _strings: {
    prefixAgo:     null,
    prefixFromNow: null,
    suffixAgo:     "ago",
    suffixFromNow: "from now",
    seconds:       "less than a minute",
    minute:        "about a minute",
    minutes:       "%d minutes",
    hour:          "about an hour",
    hours:         "about %d hours",
    day:           "a day",
    days:          "%d days",
    month:         "about a month",
    months:        "%d months",
    year:          "about a year",
    years:         "%d years",
    numbers:       [],
    wordSeparator: "",
  },
  strings: {
    prefixAgo:     null,
    prefixFromNow: "现在",
    suffixAgo:     "前",
    suffixFromNow: null,
    seconds:       "1分钟",
    minute:        "1分钟",
    minutes:       "%d分钟",
    hour:          "1小时",
    hours:         "%d小时",
    day:           "1天",
    days:          "%d天",
    month:         "1个月",
    months:        "%d月",
    year:          "1年",
    years:         "%d年",
    numbers:       [],
  }
};
